//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open_Schooling.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Db_Open_SchoolingEntities : DbContext
    {
        public Db_Open_SchoolingEntities()
            : base("name=Db_Open_SchoolingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<All_Taluka> All_Taluka { get; set; }
        public virtual DbSet<Center_Login_Information> Center_Login_Information { get; set; }
        public virtual DbSet<Tbl_District> Tbl_District { get; set; }
        public virtual DbSet<Tbl_Subject> Tbl_Subject { get; set; }
        public virtual DbSet<Tbl_CenterList> Tbl_CenterList { get; set; }
        public virtual DbSet<Tbl_Registration> Tbl_Registration { get; set; }
        public virtual DbSet<Tbl_payment> Tbl_payment { get; set; }
        public virtual DbSet<Tbl_Registration_Pre> Tbl_Registration_Pre { get; set; }
        public virtual DbSet<Tbl_Application_Form> Tbl_Application_Form { get; set; }
        public virtual DbSet<Tbl_OpenSch_Result> Tbl_OpenSch_Result { get; set; }
        public virtual DbSet<Tbl_Site_Status> Tbl_Site_Status { get; set; }
    
        public virtual int Sp_Insert_Tbl_Pay(Nullable<int> id, string first_Name, string billing_city, string billing_state, string billing_tel, string billing_email, string merchant_param1, string trans_date)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var first_NameParameter = first_Name != null ?
                new ObjectParameter("First_Name", first_Name) :
                new ObjectParameter("First_Name", typeof(string));
    
            var billing_cityParameter = billing_city != null ?
                new ObjectParameter("billing_city", billing_city) :
                new ObjectParameter("billing_city", typeof(string));
    
            var billing_stateParameter = billing_state != null ?
                new ObjectParameter("billing_state", billing_state) :
                new ObjectParameter("billing_state", typeof(string));
    
            var billing_telParameter = billing_tel != null ?
                new ObjectParameter("billing_tel", billing_tel) :
                new ObjectParameter("billing_tel", typeof(string));
    
            var billing_emailParameter = billing_email != null ?
                new ObjectParameter("billing_email", billing_email) :
                new ObjectParameter("billing_email", typeof(string));
    
            var merchant_param1Parameter = merchant_param1 != null ?
                new ObjectParameter("merchant_param1", merchant_param1) :
                new ObjectParameter("merchant_param1", typeof(string));
    
            var trans_dateParameter = trans_date != null ?
                new ObjectParameter("trans_date", trans_date) :
                new ObjectParameter("trans_date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Insert_Tbl_Pay", idParameter, first_NameParameter, billing_cityParameter, billing_stateParameter, billing_telParameter, billing_emailParameter, merchant_param1Parameter, trans_dateParameter);
        }
    
        public virtual int Sp_Insert_Tbl_Regi(string adhar_no, string dateNow)
        {
            var adhar_noParameter = adhar_no != null ?
                new ObjectParameter("Adhar_no", adhar_no) :
                new ObjectParameter("Adhar_no", typeof(string));
    
            var dateNowParameter = dateNow != null ?
                new ObjectParameter("DateNow", dateNow) :
                new ObjectParameter("DateNow", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Insert_Tbl_Regi", adhar_noParameter, dateNowParameter);
        }
    }
}
